name: send email after workflow

on:
    workflow_dispatch:

jobs:
    send_email:
        runs-on: ubuntu-latest
        steps:
            -   name: checkout code
                uses: actions/checkout@v2
                
            -   name: setup pyhton env 
                uses: actions/setup-python@v2
                with:
                    python-version: '3.x'
            -   name: Install dependencies
                run:
                    python -m pip install --upgrade pip
                  
                    
            -   name: send mail
                run: python script.py
                env:    
                    WORKFLOW_NAME: ${{ github.workflow }}
                    REPO_NAME: ${{ github.repository }}
                    WORKFLOW_RUN_ID: ${{github.run_id}}
                    SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }} #THESE ARE CONFIGURED MANUALLY INSIDE YOUR REPOSITORY
                    SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                    RECEIVER_EMAIL: ${{secrets.RECEIVER_EMAIL}}
                
            
            
